# Gruvbox light colors for i3wm
# class                 border  backgr. text    indicator
client.focused          #665c54 #ebdbb2 #1d2021 #af3a03
client.focused_inactive #bdae93 #fbf1c7 #504945 #7c6f64
client.unfocused        #d5c4a1 #fbf1c7 #665c54 #7c6f64
client.urgent           #9d0006 #fbf1c7 #1d2021 #9d0006
