# Gruvbox dark colors for i3wm
# class                 border  backgr. text    indicator
client.focused          #4e4e4e #282828 #ebdbb2 #d65d0e
client.focused_inactive #282828 #282828 #93a1a1 #586e75
client.unfocused        #282828 #282828 #93a1a1 #586e75
client.urgent           #d65d0e #282828 #000000 #586e75
