# General settings
scrollback_lines 10000
# open_url_with "/opt/firefox/firefox"
open_url_with "/dev/null"
clipboard_control read-clipboard read-primary write-clipboard write-primary

# Disable beep
enable_audio_bell no

# {{{ Keybindings
clear_all_shortcuts yes
# open_url_modifiers ctrl

# Bind Ctrl-Backspace in terminal apps
map ctrl+backspace send_text all \x17

map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
map ctrl+= change_font_size all +2.0
map ctrl+- change_font_size all -2.0
map ctrl+shift+u input_unicode_character

# Hints kitten
map ctrl+.>u                  kitten hints --type url
map ctrl+.>p                  kitten hints --type path
# }}}

# {{{ Apperance
# Use: kitty list-fonts
font_family      JetBrains Mono NL Regular Nerd Font Complete Mono
bold_font        JetBrains Mono NL Bold Nerd Font Complete Mono
italic_font      JetBrains Mono NL Italic Nerd Font Complete Mono
bold_italic_font JetBrains Mono NL Bold Italic Nerd Font Complete Mono

font_size               12
adjust_line_height      0
adjust_column_width     -1
cursor_shape            block
cursor_blink_interval   0

#: Color scheme {{{
# Gruvbox Dark
selection_foreground    #ebdbb2
selection_background    #d65d0e

background              #282828
foreground              #ebdbb2

color0                  #3c3836
color1                  #cc241d
color2                  #98971a
color3                  #d79921
color4                  #458588
color5                  #b16286
color6                  #689d6a
color7                  #a89984
color8                  #928374
color9                  #fb4934
color10                 #b8bb26
color11                 #fabd2f
color12                 #83a598
color13                 #d3869b
color14                 #8ec07c
color15                 #fbf1c7

cursor                  #bdae93
cursor_text_color       #665c54

url_color               #458588

active_tab_foreground   #eeeeee
active_tab_background   #d65d0e
inactive_tab_foreground #ebdbb2
inactive_tab_background #202020
#: }}}

# }}}

# vim:foldmethod=marker:foldenable:foldlevel=0:sw=4:tw=100:ft=conf
