#!/usr/bin/env bash
#
# Rofi helper for taskwarrior.
#

_rofi () {
    rofi -dmenu -i -no-levenshtein-sort -width 1000 "$@"
}

new_task="Alt+n"
actions="Alt+a"

add_task() {
    TMPFILE='/tmp/rofi-dmenu-taskwarrior'
    task rofi rc.verbose=nothing > $TMPFILE
    TASK=`rofi -dmenu -p "Task: " -i -input $TMPFILE`
    TASK_ID=`echo $TASK | cut -f1 -d' '`
    echo $TASK_ID > /tmp/dotask-id
    task start $TASK_ID
}

parse_task() {
    echo "$(task minimal)" | sed -e '1,3d' | sed '/^$/d' | sed '/^[0-9]/d'
}

main() {
    HELP="Taskwarrior. Use <span color='${help_color}'>${new_task}</span> to add a new Task
    <span color='${help_color}'>${actions}</span> for actions"
    content=$(parse_task)
    menu=$(echo "${content}" | _rofi -p '> ' -filter "${filter}" -mesg "${HELP}" -kb-custom-1 "${new_task}" -kb-custom-2 "${actions}")
}

main
