#!/bin/bash
#
# i3blocks widget for taskwarrior.
# Output format: <context> | <today done> | <today scheduled> | <today due>
#

function get_context {
    local ctx="$(task rc.gc=off _get rc.context)"
    if [ -z $ctx ]; then
        echo "<span color='#83a598'>?</span>"
    else
        echo "$ctx" | head -c 1 | tr a-z A-Z
    fi
}

function get_tasks {
    tasks=""

    # Count tasks
    t_done_num="$(task rc.gc=off end:today +COMPLETED -DELETED count)"
    t_sched_num="$(task rc.gc=off sched.before:today+1d -COMPLETED -DELETED -DUETODAY count)"
    t_due_num="$(task rc.gc=off due.before:today+1d -COMPLETED -DELETED count)"

    # Formate output string
    tasks="<span color='#b8bb26'>$t_done_num</span>"
    if [ "$t_sched_num" -ne "0" ]; then
        tasks=${tasks}" | <span color='#d79921'>$t_sched_num</span>"
    fi
    if [ "$t_due_num" -ne "0" ]; then
        tasks=${tasks}" | <span color='#cc241d'>$t_due_num</span>"
    fi

    echo $tasks
}

# Full text
echo "$(get_context) | $(get_tasks)"

# Short text
echo "$(get_context)"
