#!/bin/bash
#
# Simple script that shows number of active taskwarrior tasks.
# Pango markup is required to show different colors.
#

# COLOR_OK="#98971a"
COLOR_WARN="#b57614"

t_due="$(task due.before:eow+1d _unique id | wc -l)"
t_sched="$(task scheduled.before:eow+1d _unique id | wc -l)"
t_overdue="$(task +OVERDUE count)"

# Full text
echo "${t_sched}:${t_due}"

# Short text
echo "${t_due}"

# Color
if [ ${t_due} -gt 0 ]; then
    echo $COLOR_WARN
else
    echo ""
fi
