#!/usr/bin/python3
#
# Export fish history to bash/zsh compatible format.
#
import click
import os
import re


@click.command()
@click.option("--path", "-p", "fish_path", type=str, help="Path to fish history location", default="~/.local/share/fish/fish_history")
def main(fish_path):
    with open(os.path.expanduser(fish_path), errors="ignore") as f:
        for line in f:
            line = line.strip()
            if line and re.match('^- cmd:.*', line):
                print(line[7:])


if __name__ == "__main__":
    main()

# vim:ft=python:
