[icons]
name = "awesome"

[theme]
name = "gruvbox-dark"
[theme.overrides]
separator=""
idle_bg = "#282828"
idle_fg = "#bdae93"
info_bg = "#282828"
info_fg = "#83a598"
warning_bg = "#282828"
warning_fg = "#d79921"
good_bg = "#282828"
good_fg = "#689d6a"
critical_bg = "#282828"
critical_fg = "#cc241d"

[[block]]
block = "sound"

[[block]]
block = "custom"
command = "if [[ -f /tmp/dunst-notifications-disabled ]]; then echo ; fi"
on_click = "/home/jubnzv/Scripts/i3/toggle-notifications"
interval = 10

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
# show_percentage = true
unit = "Percent"
interval = 30
warning = 15
alert = 5

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{MUp}%"
clickable = false
interval = 5

[[block]]
block = "cpu"
interval = 3

[[block]]
block = "custom"
command = "if [[ $(systemctl show --property ActiveState docker | egrep '=active') ]]; then echo d: $(docker ps -q | wc -l); fi"
interval = 60

# [[block]]
# block = "load"
# interval = 3
# format = "{1m}"

# [[block]]
# block = "taskwarrior"
# interval = 30

# [[block]]
# block = "custom"
# command = "echo  `task rc.gc=off sched.before:today+1d -COMPLETED -DELETED -DUETODAY count`"
# interval = 60

[[block]]
block = "battery"
interval = 15
format = "{percentage}% {time}"

[[block]]
block = "time"
format = "%H:%M"
interval = 60

