#!/usr/bin/env bash

if [[ ! -x "$(command -v task)" ]]; then
    echo "task: command not found"
    exit 1
fi

context=`task rc.gc=off _get rc.context`
if [[ $context != "" ]]; then
    context="($context)"
fi

task_body=`task minimal +ACTIVE | sed '4q;d' | awk -F' ' '{ $2=""};1'`
task_id=`echo $task_body | awk '{ print $1 }'`
task_desc=`echo $task_body | awk '{ $1=""; print }' | awk '{$1=$1};1'`

notify-send "Active task: ${task_id} ${context}" "${task_desc}" -i task-due
